
baseURL = "https://pmikus.github.io/"
googleanalytics = ""
disqusShortname = ""
disableKinds = ["taxonomy", "section"]

[module]
[[module.imports]]
path = "github.com/pmikus/hugo-theme-massively"

[params]
  # set to change date format
  dateFormat = "2.1.2006"
  # backgroundPath = "images/bg.jpg"

# Below parameters can be set to override default post settings
# [params.posts]
#     folderName = "post"
#     pageSize = "6"
#     featuredPost = "true"
#     paginationPages = 2
#     showFirstLast = false

[languages]
[languages.en]
  languageName = "English"
  languageCode = "en-us"
  title = "Bauty salon"
[languages.sk]
  languageName = "Slovak"
  languageCode = "sk-sk"
  title = "Bauty salon"