languageCode = "en-us"
title = "Hugo template repository"
baseURL = "https://pmikus.github.io/"
theme = "hugo-theme-massively"
googleanalytics = ""
disqusShortname = ""
disableKinds = ["taxonomy", "section"]

[module]
[[module.imports]]
path = "github.com/pmikus/hugo-theme-massively"

[params]
  # set to change date format
  dateFormat = "2.1.2006"
  # backgroundPath = "images/bg.jpg"

# Below parameters can be set to override default post settings
# [params.posts]
#     folderName = "post"
#     pageSize = "6"
#     featuredPost = "true"
#     paginationPages = 2
#     showFirstLast = false
